FRONTENDSCHOOL5/final-12-spport

src/App.js, src/style/GlobalStyles.js
root 안에 sns에서 쓰이는 로그인 버튼 색깔빼고 전부 추가했습니다. 색깔 사용은 변수를 이용해주세요.
=> 💄Design: GlobalStyles 추가

src/components/Common/Button/Button.jsx
=> 공통 컴포넌트 (버튼)

src/components/Common/NavBar.jsx, src/components/Common/ProfileImage.jsx
=> 공통 컴포넌트(Nav Bar, Profile Image)

.eslintrc.json
=> 📦Chore: eslint 설정 변경

src/components/List/Card.jsx, src/components/List/CardList.jsx, src/components/List/GameListItem.js, src/components/List/PlayerListItem.js, src/components/List/UserList.js, src/components/List/UserListItem.js, src/components/Post/Post.jsx, src/components/Post/PostProfile.jsx, src/routes/Router.jsx
=> [Design, Feat] List 컴포넌트, 공통 컴포넌트 작업

src/api/CommonAPI.js, src/pages/AddGame.jsx
-
- Common API 사용방법은 문서를 참고해주세요!
=> ✨Feat: Common API 추가

src/components/Common/Button/SnsButton.jsx, src/components/Common/Input.jsx
=> [Design] Input 및 SnsButton 컴포넌트 

src/pages/Login.jsx, src/pages/Signup.jsx, src/pages/Welcome.jsx
=> [Feat, Design] Welcome, Login, Signup 페이지

src/components/Comment/ViewComment.jsx
=> [✨Feat] ViewComment 컴포넌트 추가

src/api/GameAPI/AddGameAPI.js, src/api/GameAPI/LikeGameAPI.js, src/components/List/GameListItem.jsx, src/pages/AddGame.jsx
=> [Feat] 일정추가 페이지

package-lock.json, package.json, src/atom/atom.jsx, src/pages/Login.jsx
=> [Feat, Chore] Recoil 추가

src/api/GameAPI/AddGameAPI.js, src/atom/atom.jsx, src/components/Comment/InputComment.jsx, src/components/List/GameListItem.jsx, src/components/Post/BtnGroup.jsx, src/pages/AddGame.jsx, src/pages/Login.jsx, src/pages/Post.jsx
=> [Feat] test_token 삭제 및 token 연결

src/components/Comment/InputComment.jsx, src/components/Common/Button/SnsButton.jsx, src/components/Common/Empty.jsx, src/pages/Error.jsx, src/pages/Home.jsx, src/pages/Post.jsx, src/routes/Router.jsx
=> [Feat] Error 페이지 및 Empty 컴포넌트 완성

src/App.js, src/components/Comment/InputComment.jsx, src/components/Common/BottomSheet.jsx, src/components/Common/Empty.jsx, src/components/Common/Modal.jsx, src/components/List/CardList.jsx, src/components/Profile/CommonProfile.jsx, src/components/Profile/UserProfile.jsx, src/pages/AddGame.jsx, src/pages/Error.jsx, src/pages/Follow.jsx, src/pages/Home.jsx, src/pages/Login.jsx, src/pages/Post.jsx, src/pages/Profile.jsx, src/pages/Search.jsx, src/pages/Signup.jsx, src/pages/Welcome.jsx, src/style/GlobalStyles.js
=> [Design]  화면 390px로 고정 디자인

src/pages/Splash.jsx, src/pages/Welcome.jsx, src/routes/Router.jsx
=> [Refactor] Welcome, Splash, Router 

src/pages/Upload.jsx
=> 🐛Fix: 이미지 여러개 업로드 및 토큰 수정

src/api/FollowAPI.js, src/components/Profile/CommonProfile.jsx, src/components/Profile/TeamProfile.jsx, src/components/Profile/UserProfile.jsx
=> [Feat] 팔로우 기능 추가(팔로잉, 팔로워 페이지 제외)

src/api/AddProductAPI.js, src/api/ProfileAPI.js, src/components/Post/PostList.jsx, src/components/Profile/UserProfile.jsx, src/pages/Home.jsx
=> [Feat] 유저 프로필 내 포스트 리스트 추가

src/components/Common/Button/ImageButton.jsx
=> 🐛Fix: ImageButton 기능 수정

src/atom/loginAtom.jsx, src/components/Common/Header/Header.jsx, src/pages/EditProfile.jsx, src/pages/Login.jsx, src/pages/Signup.jsx
=> [Feat, Refactor, Fix] 회원가입, Header, 프로필 수정,  아톰, 로그인

src/atom/loginAtom.jsx, src/components/Common/Header/Header.jsx, src/pages/EditProfile.jsx, src/pages/Login.jsx, src/pages/Signup.jsx
=> [Comment] 불필요한 코드 삭제

.eslintrc.json, src/components/Follow/FollowList.jsx, src/components/Follow/Followers.jsx, src/components/Follow/Followings.jsx, src/components/Profile/UserProfile.jsx, src/pages/Follow.jsx
=> [Feat, Fix, Refactor] 팔로우 기능 구현(팔로워, 팔로잉 페이지), 팔로우 함수 이름 변경, 팔로우 버튼 조건수정

src/components/Common/Button/ImageButton.jsx
=> 🐛Fix: 이미지버튼과 업로드버튼 수정

src/components/Profile/UserProfile.jsx
=> [Fix] 다른 사람 게시물 불러오는 코드 복구

src/components/Common/Button/ImageButton.jsx, src/pages/EditPost.jsx, src/pages/Upload.jsx
=> 🐛Fix: UploadButton 수정 및 Upload페이지 수정 ✨Feat: EditPost 페이지 추가

src/components/Comment/InputComment.jsx, src/components/Common/Header/Header.jsx, src/pages/Chat.jsx, src/pages/ChatRoom.jsx
=> [Feat, Design] Chat, ChatRoom, Header, InputComment

src/api/AddProductAPI.js, src/api/PostAPI.js/CommentAPI.js, src/components/Comment/CommentList.jsx, src/components/Common/Empty.jsx, src/components/Common/Modals/BottomSheet.jsx, src/components/Post/GamePost.jsx, src/components/Post/Post.jsx, src/components/Post/PostList.jsx, src/components/Post/RegularPost.jsx, src/components/Profile/UserProfile.jsx, src/pages/Home.jsx
=> [Feat, Fix] Swiper 수정, 무한 스크롤 추가

src/pages/EditPost.jsx, src/pages/Upload.jsx
=> 🐛Fix: 사진 업로드 취소 시 에러 수정 및 코드 정리

src/pages/PlayerList.jsx
=> [Design] PlayerList 페이지 수정

src/components/Profile/CommonProfile.jsx, src/components/Profile/MyProfile.jsx, src/components/Profile/ProfleStyle.jsx
=> [Feat] 태그 눌렀을 시 search로 이동

src/components/Common/Input.jsx, src/pages/Splash.jsx, src/pages/Welcome.jsx
=> [Fix, Design] Input, Splash, Welcome

src/components/Comment/ViewComment.jsx, src/components/Post/GamePost.jsx, src/components/Post/RegularPost.jsx
=> [Feat, Fix] 댓글 아이디 클릭시 프로필 이동, 게시글 상세 페이지 컨텐츠의 링크 삭제

src/api/SearchAPI.js, src/components/Comment/ViewComment.jsx, src/components/Common/Empty.jsx, src/components/Post/Post.jsx, src/pages/Upload.jsx
=> [Design, Fix] 마이너 버그/디자인 변경

README.md
=> 📝Docs: Update README.md

src/components/Comment/ViewComment.jsx
=> React query

README.md
=> 📝Docs: 배포 주소 수정

src/components/List/CardGrid.jsx, src/components/Profile/ProfleStyle.jsx, src/pages/EditProfile.jsx, src/pages/Signup.jsx
=> [Design] 반응형

src/hook/usePost.js, src/hook/useProfile.js, src/pages/Home.jsx, src/pages/Post.jsx, src/pages/Profile.jsx
=> [Fix] 리액트쿼리 관련 버그 수정

src/components/Common/NavBar.jsx, src/components/Post/BtnGroup.jsx, src/components/Post/PostList.jsx, src/components/Profile/CommonProfile.jsx, src/components/Profile/MyProfile.jsx, src/components/Profile/TeamProfile.jsx, src/components/Profile/UserProfile.jsx, src/pages/EditProfile.jsx, src/pages/Home.jsx, src/pages/Profile.jsx
=> [Design,Feat,Fix] 내브바 추가, 프로필 수정 버그 수정

src/components/Common/Header/Header.jsx, src/components/Common/Header/SearchBox.jsx, src/pages/AddGame.jsx, src/pages/Follow.jsx, src/pages/Home.jsx, src/pages/Post.jsx, src/pages/Schedule.jsx, src/pages/Search.jsx
=> [Design, Feat] 반응형

src/components/Common/Header/SearchBox.jsx
=> [Fix] 검색이 3글자 이상 입력되었을 때만 되도록 수정

src/App.js, src/components/Post/Post.jsx, src/index.js, src/pages/AddGame.jsx, src/pages/EditPost.jsx, src/pages/EditProfile.jsx, src/pages/Follow.jsx, src/pages/PlayerList.jsx, src/pages/Post.jsx, src/pages/Profile.jsx, src/pages/Schedule.jsx, src/pages/Upload.jsx
=> [Feat, Fix] 팔로워, 팔로잉 페이지 헤더 변경, meta 태그 및 타이틀 추가, 댓글 입력 버그 수정

package-lock.json, package.json
=> [Chore] package/package-lock.json

src/api/WeatherAPI.js, src/components/Post/GamePost.jsx, src/components/Skeleton/CardLoader.jsx, src/components/Skeleton/GameLoader.jsx, src/components/Skeleton/PostLoader.jsx, src/components/Skeleton/TeamProfileLoader.jsx, src/components/Skeleton/UserProfileLoader.jsx
=> [Design] 스켈레톤 반응형 작업

src/pages/PlayerList.jsx
=> [Feat] PlayerList 축구, 배구 선수정보 알 수 있도록 수정

src/pages/Login.jsx
=> [Refactor] 로그인 수정

.github/workflows/main.yml
=> 📦Chore: Update main.yml
